import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import AuthProvider from '@/provider/AuthProvider';
import AdminLayout from '@/components/AdminLayout';
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={`bg-black text-white ${geistSans.variable} ${geistMono.variable}`}>
        <ClerkProvider>
          <AuthProvider>
            <AdminLayout>
            {children}
            </AdminLayout>
          </AuthProvider>
        </ClerkProvider>

        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}